### ISSUE TITLE
Training phase

### ISSUE THREAD

**Issue by OrEitan2** [liyongqi67/MINDER#1]
Hello,

Firstly, I'd like to express my gratitude for sharing the repository; it has been instrumental in enhancing my understanding. 
I'm curious to know if you intend to provide instructions on training the model from scratch using the MSMARCO dataset. 
While I noticed the mention of downloading data from the drive, specifically `data/training_data/NQ_title_body_query_generated/bin`, it appears to be a pre-processed file. 
Would you be providing steps for how to train it from the initial?

Thank you.

**Comment by liyongqi67** [comment]
Hi, I updated the data processing instruction in https://github.com/liyongqi67/MINDER/blob/main/scripts/training/README.md.
